services:
  dev-utilities:
    build:
      context: .
      dockerfile: Dockerfile # Tells Compose to use your Dockerfile
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules # This keeps the container's node_modules separate
    stdin_open: true
    tty: true