version: '3.8'

services:
  dev-utilities:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-80}:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production