version: '3.8'

services:
  dev-utilities:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: npm start

  # Optional: Add nginx for production-like serving
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dev-utilities
    profiles:
      - production

volumes:
  node_modules:
